### ISSUE TITLE
Add a BroadleafWebTemplateResolver for non-theme webapp clients

### ISSUE THREAD

**Issue by ncrum** [BroadleafCommerce/PresentationLayer#12]
`blAdminWebTemplateResolver` needs to be changed to be some sort of web template resolver and not of "theme" type.

**Comment by ncrum** [comment]
We might need to do this in the site template config for `blWebTemplateResolver`. I'm not certain that the `ThemeAwareTemplateResolver` works in the site context if you don't have theme. Even if it does just happen to work, shouldn't we probably have a `BroadleafWebTemplateResolver` be used instead? What if a client wants to use theme AND wants to use a non-theme template folder?

**Comment by cja769** [comment]
The `BroadleafThymeleaf3ThemeAwareTemplateResolver` is null safe for application that don't have a theme. Could be renamed but at this point it'd be a migration for clients that use the class that yields little benefit.
